# Generated by Django 4.1.6 on 2023-04-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_de_nacimiento', models.CharField(max_length=40)),
                ('antiguedad', models.IntegerField(default=0)),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appEmpresaDjango.departamento')),
                ('Habilidades', models.ManyToManyField(to='appEmpresaDjango.habilidades')),
            ],
        ),
    ]
